apiVersion: v1
kind: Pod
metadata:
  name: myconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo welcome to k8s; sleep 2; done"]
    volumeMounts:
      - name: testconfigmap
        mountPath: "/tmp/config"
  volumes:
  - name: testconfigmap
    configMap:
       name: mymap
       items:
       - key: sample.conf
         path: sample.conf
