apiVersion: v1
kind: Pod
metadata:
  name: mysecrete
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo welcome to k8s; sleep 2; done"]
    volumeMounts:
      - name: testsecret
        mountPath: "/tmp/secretes"
  volumes:
  - name: testsecret
    secret:
      secretName: mysecrets

