apiVersion: v1
kind: Pod
metadata:
  name: flipkart
spec:
  containers:
  - name: signup
    image: amazonlinux
    command: ["/bin/bash", "-c", "while true; do echo ravi; sleep 2; done"]
  - name: login
    image: nginx
    ports:
      - containerPort: 80


