apiVersion: v1
kind: ReplicationController
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: amit
      labels:
        app: nginx
    spec:
      containers:
        - name: signup
          image: nginx
          ports:
          - containerPort: 80
